---
providers:
- name: openrouteservice
  base_url: https://api.openrouteservice.org/geocode
  key: "5b3ce3597851110001cf6248d6395a4eb976474fade1638b2fc1752c"
  limit: 40
  unit: minute
  endpoints:
    search: "/search"
    structured: "/search/structured"
    reverse: "/reverse"
- name: "geocode.earth"
  base_url: https://api.geocode.earth/v1
  key: "ge-9d9b107fb41ef704"
  limit: 10
  unit: second
  endpoints:
    search: "/search"
    structured: "/search/structured"
    reverse: "/reverse"
